# STORED (DISABLED BY DEFAULT): GitHub Actions are OFF for cost control.
# To enable: copy this file to .github/workflows/governance-ci.yml and enable Actions in repo settings.
# To disable again: move it back into /githubactions/workflows/.

name: Governance CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure scripts executable
        run: |
          chmod +x scripts/*.sh || true

      - name: Generate optional derived TODO (non-binding)
        run: |
          ./scripts/sync-todo.sh
          git diff --exit-code TODO.md

      - name: Governance audit
        run: ./scripts/ai-audit.sh

      - name: Security scan
        run: ./scripts/security-scan.sh

      - name: Best-effort checks
        run: ./scripts/check.sh
